encoder:
    encoder_type: vit
    # Zero Agnostic (Hyperkernel takes raw pixels)
    ma_layers_blocks: [] 
    ma_embedding_dims: [] 
    # Hyperkernel as Tokenizer (8x downsampling)
    hyperkernel_config:
      input_dim: 1 # Raw Pixel
      embedding_dim: 384
      kernel_size: 8
      padding: 0
      stride: 8
      use_bias: true

    vit_config:
        image_size: 16      # 128 / 8 = 16
        patch_size: 1       # 1x1 conv inside ViT
        num_layers: 12
        num_heads: 6
        hidden_dim: 384
        mlp_dim: 1536       # 4 * hidden_dim
        dropout: 0.0
        attention_dropout: 0.0

decoder:
  decoder_type: vit
  decoded_embed_dim: 384
  num_blocks: 1
  vit_config:
      num_heads: 6
  hyperkernel_config:
      kernel_size: 1
      padding: 0
      stride: 1
      use_bias: true

panel_config: configs/all_panels_config.yaml
tokenizer_config: configs/all_markers_tokenizer.yaml
input_image_size: [128, 128]
num_workers: 8
batch_size: 8
device: cuda
lr: 5e-4
final_lr: 1e-5
weight_decay: 0.0001
gradient_accumulation_steps: 1
epochs: 10
frac_warmup_steps: 0.1
min_channels_frac: 0.75
spatial_masking_ratio: 0.6
fully_masked_channels_max_frac: 0.5
mask_patch_size: 8
from_checkpoint: null
checkpoints_dir: checkpoints
save_checkpoint_freq: 5
tags: [...]
neptune_project: ...
neptune_api_token: ...
