encoder:
    encoder_type: swin
    ma_layers_blocks: [6,]
    ma_embedding_dims: [16,]
    pm_layers_blocks: [6, 6]
    pm_embedding_dims: [384, 768]

    hyperkernel_config:
      input_dim: 16
      embedding_dim: 192
      kernel_size: 1
      padding: 0
      stride: 1
      use_bias: true

decoder:
  decoder_type: vit
  decoded_embed_dim: 512
  num_blocks: 1

  hyperkernel_config:
      # embedding_dim == decoded_embed_dim
      kernel_size: 1
      padding: 0
      stride: 1
      use_bias: true

# Data configuration
panel_config: configs/zero_panels_config.yaml
tokenizer_config: configs/all_markers_tokenizer.yaml
input_image_size: [128, 128]
num_workers: 8
batch_size: 8

# Training configuration
device: cuda
lr: 5e-4
final_lr: 5e-7
weight_decay: 0.005
gradient_accumulation_steps: 1
epochs: 200
frac_warmup_steps: 0.025
min_channels_frac: 0.75
spatial_masking_ratio: 0.6
fully_masked_channels_max_frac: 0.5
mask_patch_size: 8
from_checkpoint: null
checkpoints_dir: checkpoints
save_checkpoint_freq: 10

tags: [...]
neptune_project: ...
neptune_api_token: ...