ADAR1: 0
AKT: 1
AMY1A: 2
AMY2A: 3
Annexin A2: 4
anti-Hu: 5
ANXA1: 6
AR: 7
Arg1: 8
ARX: 9
ATP5A: 10
ATPIF1: 11
AXL: 12
B2M: 13
BCAN: 14
Bcl2: 15
beta-Actin: 16
beta-Catenin: 17
Biotin: 18
c-Caspase3c-PARP: 19
c-Myc: 20
C-peptide: 21
C1Qa: 22
C3: 23
CA2: 24
Cadherin-11: 25
Carbonic Anhydrase: 26
Caveolin-1: 27
CCL18: 28
CCL19: 29
CCL2: 30
CCL21: 31
CCL22: 32
CCL4: 33
CCL8: 34
CCR2: 35
CCR4: 36
CCR6: 37
CD10: 38
CD103: 39
CD109: 40
CD11b: 41
CD11c: 42
CD134: 43
CD137: 44
CD14: 45
CD146: 46
CD15: 47
CD155: 48
CD16: 49
CD163: 50
CD19: 51
CD20: 52
CD204: 53
CD206: 54
CD209: 55
CD235ab: 56
CD248: 57
CD27: 58
CD276: 59
CD3: 60
CD303: 61
CD31: 62
CD31-vWF: 63
CD33: 64
CD34: 65
CD36: 66
CD38: 67
CD39: 68
CD4: 69
CD40: 70
CD44: 71
CD45: 72
CD45RA: 73
CD45RO: 74
CD47: 75
CD54: 76
CD56: 77
CD57: 78
CD66a: 79
CD66b: 80
CD68: 81
CD69: 82
CD7: 83
CD73: 84
CD74: 85
CD79A: 86
CD86: 87
CD8a: 88
CD9: 89
CD94: 90
CD99: 91
CDX2: 92
CEACAM5: 93
CFTR: 94
CHGA: 95
CHI3L1: 96
Cirate Synthase: 97
CK14: 98
CK19: 99
CK20: 100
CK5: 101
CK7: 102
CK8-18: 103
cl.PARP: 104
Collagen Type I: 105
CTLA-4: 106
CXCL10: 107
CXCL12: 108
CXCL13: 109
CXCL4: 110
CXCL8: 111
CXCL9: 112
CXCR2: 113
CXCR5: 114
CXCR6: 115
DapB: 116
DCSIGN: 117
DLL3: 118
DNA1: 119
DNA2: 120
Ecad: 121
EGFR: 122
EOMES: 123
EPCAM: 124
ER: 125
ERK: 126
ERN1: 127
EZH2: 128
FAP: 129
Fibrinogen: 130
Fibronectin: 131
FOXA2: 132
FOXP3: 133
FSP1: 134
GAPDH: 135
GATA3: 136
GCG: 137
GFAP: 138
GHRL: 139
GITR: 140
GLUT1: 141
GPA33: 142
GrzB: 143
HER2 (3B5): 144
HER2 (D8F12): 145
HER3: 146
Hexokinase I: 147
HIF1a: 148
Histone H3: 149
Histone H3 - p: 150
Histone H3 - t: 151
Histone H3 k27me3: 152
HLA-ABC: 153
HLADR: 154
HOPX: 155
IAPP: 156
IBA1: 157
ICOS: 158
Ido1: 159
IFNy: 160
IgG: 161
IL10: 162
IL17a: 163
IL7a: 164
Insulin: 165
JARID2-C: 166
JARID2-N: 167
K-Cadherin: 168
Ki67: 169
Ki67-pt198: 170
LAG3: 171
LAMP3: 172
LDHA: 173
LYVE1: 174
MART1: 175
Met: 176
MITF: 177
MMP11: 178
MMP9: 179
MOG: 180
MPO: 181
MS4A4A: 182
mTOR: 183
MX1: 184
NaK-ATPase: 185
Nestin: 186
NeuN: 187
NFkb: 188
NKG2A: 189
NKp46: 190
NKX2.2: 191
NKX6-1: 192
Olig1: 193
Olig2: 194
P2RY12: 195
p53: 196
p75: 197
pAKT: 198
panCK: 199
Pax6: 200
pCREB: 201
PCSK1: 202
PCSK2: 203
PD1: 204
PDGFRb: 205
PDL1: 206
PDX1: 207
pERK: 208
PIN: 209
PM2: 210
PM3: 211
PM4: 212
pMAPKAPK2: 213
PNAd: 214
pNFkB: 215
Podoplanin: 216
PP: 217
pp38: 218
PPY: 219
PR: 220
pRB: 221
Proglucagon: 222
Proinsulin: 223
pS6: 224
pSTAT1: 225
pSTAT3: 226
PTEN: 227
PTPN22: 228
PTPRN: 229
S100a8: 230
S100B: 231
S6: 232
SCD5: 233
SLC1A3/EAAT1: 234
Slug: 235
SMA: 236
SNAI1: 237
SOD2: 238
Somatostatin: 239
Sox10: 240
Sox2: 241
Sox9: 242
SYP: 243
TBET: 244
TCF1: 245
TCF1/7: 246
TCF7: 247
TGFB: 248
TIGIT: 249
Tim3: 250
TMEM119: 251
TMEM173: 252
TNC: 253
TOX: 254
TOX2: 255
Twist: 256
TXNIP: 257
VCAM1: 258
VEGF: 259
Vimentin: 260
VISTA: 261
vWF: 262
WFS1: 263
XBP1: 264
