paths:
  train: /raid/immucan/immuvis_splits/train
  test: /raid/immucan/immuvis_splits/test
datasets:
- ajaib
- bc2
- bengsch
- bowen-lynch
- cho_2025
- cords
- cords-fibro
- damond-lung
- danenberg
- ehret_2025_p1
- ehret_2025_p2
- einhaus_2025
- haley_glio
- hn
- hoch-protein
- hoch-rna
- jackson-basel
- jackson-zurich
- kucukkose
- nsclc2-panel1
- nsclc2-panel2
- ohara
- steenbuck-immune
- steenbuck-islets
- susman
- xu
clip_limits:
  ajaib: 4.9
  bc2: 3.7
  bengsch: 0.1
  bowen-lynch: 3.2
  cho_2025: 3.9
  cords: 4.0
  cords-fibro: 2.3
  damond-lung: 2.1
  danenberg: 2.9
  ehret_2025_p1: 3.4
  ehret_2025_p2: 2.4
  einhaus_2025: 2.4
  haley_glio: 2.5
  hn: 3.4
  hoch-protein: 3.8
  hoch-rna: 3.5
  jackson-basel: 2.3
  jackson-zurich: 2.4
  kucukkose: 2.8
  nsclc2-panel1: 3.1
  nsclc2-panel2: 2.7
  ohara: 3.6
  steenbuck-immune: 1.9
  steenbuck-islets: 2.6
  susman: 4.0
  xu: 2.3
markers:
  steenbuck-islets:
  - ADAR1
  - AMY1A
  - ARX
  - ATPIF1
  - B2M
  - Biotin
  - C-peptide
  - C3
  - Carbonic Anhydrase
  - Caveolin-1
  - CD155
  - CD163
  - CD3
  - CD9
  - CFTR
  - CHGA
  - CK19
  - DNA1
  - DNA2
  - Ecad
  - ERN1
  - FOXA2
  - GCG
  - GHRL
  - Histone H3
  - HLA-ABC
  - IAPP
  - Insulin
  - Ki67
  - MX1
  - NFkb
  - NKX2.2
  - NKX6-1
  - Pax6
  - PCSK1
  - PCSK2
  - PDL1
  - PDX1
  - PPY
  - Proglucagon
  - Proinsulin
  - Somatostatin
  - SYP
  - TXNIP
  - Vimentin
  - WFS1
  - XBP1
  kucukkose:
  - AKT
  - beta-Catenin
  - c-Caspase3c-PARP
  - CD14
  - CD16
  - CD20
  - CD3
  - CD4
  - CD45
  - CD45RO
  - CD68
  - CD8a
  - CTLA-4
  - Ecad
  - ERK
  - FOXP3
  - GrzB
  - Histone H3
  - ICOS
  - IFNy
  - IL10
  - IL17a
  - Ki67
  - LAG3
  - NFkb
  - pAKT
  - panCK
  - PD1
  - PDL1
  - pERK
  - pS6
  - pSTAT3
  - SMA
  - TBET
  damond-lung:
  - AMY2A
  - c-Caspase3c-PARP
  - Carbonic Anhydrase
  - CD20
  - CD3
  - CD31
  - CD38
  - CD4
  - CD44
  - CD45
  - CD45RA
  - CD68
  - CD8a
  - CD99
  - CK19
  - DNA1
  - DNA2
  - Ecad
  - FOXP3
  - GCG
  - GLUT1
  - Histone H3
  - Histone H3 - p
  - IAPP
  - Insulin
  - Ki67
  - MPO
  - NKX6-1
  - PCSK2
  - PDX1
  - PIN
  - PPY
  - pRB
  - PTPRN
  - SMA
  - SYP
  ajaib:
  - Annexin A2
  - ANXA1
  - BCAN
  - CD3
  - CD31
  - CD45
  - CD56
  - CD8a
  - CHI3L1
  - DLL3
  - DNA1
  - DNA2
  - EZH2
  - GFAP
  - HIF1a
  - HOPX
  - IBA1
  - JARID2-C
  - JARID2-N
  - Ki67
  - MOG
  - NeuN
  - NKp46
  - Olig1
  - P2RY12
  - SCD5
  - SLC1A3/EAAT1
  - SMA
  - SNAI1
  - SOD2
  - Sox2
  - TGFB
  - TMEM119
  - TNC
  ehret_2025_p1:
  - Arg1
  - beta-Catenin
  - c-Caspase3c-PARP
  - Carbonic Anhydrase
  - Caveolin-1
  - CD15
  - CD163
  - CD20
  - CD3
  - CD31
  - CD4
  - CD45
  - CD56
  - CD68
  - CD8a
  - CDX2
  - CEACAM5
  - CK20
  - CK8-18
  - DNA1
  - DNA2
  - EGFR
  - FOXP3
  - FSP1
  - GATA3
  - GPA33
  - GrzB
  - HER2 (3B5)
  - HER3
  - HLA-ABC
  - HLADR
  - Ki67
  - LAG3
  - p53
  - panCK
  - PD1
  - PDL1
  - Podoplanin
  - PTEN
  - SMA
  - TBET
  - Vimentin
  ehret_2025_p2:
  - Arg1
  - c-Caspase3c-PARP
  - Carbonic Anhydrase
  - Caveolin-1
  - CD11c
  - CD137
  - CD15
  - CD163
  - CD20
  - CD3
  - CD31
  - CD38
  - CD4
  - CD40
  - CD45
  - CD56
  - CD68
  - CD7
  - CD73
  - CD79A
  - CD8a
  - CTLA-4
  - DNA1
  - DNA2
  - FOXP3
  - FSP1
  - GrzB
  - HLA-ABC
  - HLADR
  - Ido1
  - Ki67
  - LAG3
  - panCK
  - PD1
  - PDL1
  - Podoplanin
  - SMA
  - TBET
  - TCF1/7
  - Tim3
  - TMEM173
  - TOX2
  - Vimentin
  - VISTA
  cho_2025:
  - Arg1
  - CD134
  - CD137
  - CD15
  - CD163
  - CD20
  - CD206
  - CD3
  - CD4
  - CD45RA
  - CD45RO
  - CD47
  - CD57
  - CD68
  - CD73
  - CD74
  - CD86
  - CD8a
  - Collagen Type I
  - DCSIGN
  - DNA1
  - DNA2
  - FOXP3
  - GrzB
  - HLADR
  - ICOS
  - Ki67
  - LAG3
  - panCK
  - PD1
  - PDL1
  - PM2
  - PM3
  - PM4
  - Podoplanin
  - pSTAT3
  - PTPN22
  - TIGIT
  - Tim3
  - TOX
  - VISTA
  steenbuck-immune:
  - Arg1
  - ATP5A
  - Caveolin-1
  - CD103
  - CD11b
  - CD11c
  - CD15
  - CD16
  - CD163
  - CD20
  - CD204
  - CD206
  - CD27
  - CD3
  - CD303
  - CD4
  - CD45RA
  - CD45RO
  - CD54
  - CD56
  - CD57
  - CD66b
  - CD7
  - CD73
  - CD8a
  - Cirate Synthase
  - DNA1
  - DNA2
  - FOXP3
  - GCG
  - GrzB
  - Hexokinase I
  - Histone H3
  - HLADR
  - Insulin
  - Ki67
  - LDHA
  - MPO
  - NKX6-1
  - PD1
  - PDX1
  - SMA
  - Somatostatin
  - SYP
  - Tim3
  - TMEM173
  - Vimentin
  nsclc2-panel2:
  - Arg1
  - Bcl2
  - CD10
  - CD11b
  - CD11c
  - CD134
  - CD137
  - CD146
  - CD15
  - CD155
  - CD20
  - CD204
  - CD209
  - CD3
  - CD31
  - CD45
  - CD56
  - CD66b
  - CD7
  - CD73
  - CD8a
  - CXCL13
  - CXCL8
  - DNA1
  - DNA2
  - Ecad
  - EGFR
  - EOMES
  - FOXP3
  - GATA3
  - GITR
  - Histone H3
  - IgG
  - Ki67
  - LAMP3
  - MMP9
  - NKG2A
  - p53
  - panCK
  - PD1
  - Podoplanin
  - SMA
  - TBET
  - Tim3
  xu:
  - AXL
  - Carbonic Anhydrase
  - CCR4
  - CD11b
  - CD11c
  - CD134
  - CD14
  - CD16
  - CD20
  - CD27
  - CD3
  - CD38
  - CD4
  - CD45
  - CD68
  - CD74
  - CD8a
  - Collagen Type I
  - DNA1
  - DNA2
  - Ecad
  - EPCAM
  - FAP
  - FOXP3
  - HLADR
  - ICOS
  - Ido1
  - IL7a
  - Ki67
  - LAG3
  - PD1
  - PDGFRb
  - PDL1
  - SMA
  - Tim3
  - VEGF
  - Vimentin
  hoch-rna:
  - B2M
  - Cadherin-11
  - CCL18
  - CCL19
  - CCL2
  - CCL22
  - CCL4
  - CCL8
  - CCR2
  - CD134
  - CD15
  - CD163
  - CD3
  - CD31
  - CD38
  - CD68
  - CD8a
  - CK5
  - cl.PARP
  - CXCL10
  - CXCL12
  - CXCL13
  - CXCL8
  - CXCL9
  - DapB
  - DNA1
  - DNA2
  - FAP
  - GLUT1
  - Histone H3
  - HLADR
  - LAG3
  - MART1
  - MPO
  - PD1
  - PDL1
  - pRB
  - S100B
  - SMA
  - Sox10
  - Vimentin
  bowen-lynch:
  - B2M
  - CCR6
  - CD11b
  - CD11c
  - CD134
  - CD137
  - CD14
  - CD163
  - CD19
  - CD276
  - CD3
  - CD33
  - CD39
  - CD4
  - CD45
  - CD45RO
  - CD66b
  - CD68
  - CD73
  - CD8a
  - CD94
  - DNA1
  - DNA2
  - FOXP3
  - GAPDH
  - GrzB
  - HLADR
  - ICOS
  - Ido1
  - Ki67
  - LAG3
  - MPO
  - NaK-ATPase
  - panCK
  - PD1
  - PDL1
  - Tim3
  - VISTA
  hn:
  - B2M
  - Carbonic Anhydrase
  - CD11c
  - CD14
  - CD15
  - CD16
  - CD163
  - CD20
  - CD206
  - CD27
  - CD3
  - CD303
  - CD33
  - CD38
  - CD4
  - CD40
  - CD45RA
  - CD45RO
  - CD68
  - CD7
  - CD8a
  - cl.PARP
  - DNA1
  - DNA2
  - Ecad
  - FOXP3
  - GrzB
  - Histone H3
  - HLADR
  - ICOS
  - Ido1
  - Ki67
  - LAG3
  - MPO
  - PD1
  - PDGFRb
  - PDL1
  - SMA
  - TCF7
  - VISTA
  nsclc2-panel1:
  - B2M
  - Carbonic Anhydrase
  - CD11c
  - CD14
  - CD15
  - CD16
  - CD163
  - CD20
  - CD206
  - CD27
  - CD3
  - CD303
  - CD33
  - CD38
  - CD4
  - CD40
  - CD45RA
  - CD45RO
  - CD68
  - CD7
  - CD8a
  - cl.PARP
  - DNA1
  - DNA2
  - Ecad
  - FOXP3
  - GrzB
  - Histone H3
  - HLADR
  - ICOS
  - Ido1
  - Ki67
  - LAG3
  - MPO
  - PD1
  - PDGFRb
  - PDL1
  - SMA
  - TCF7
  - VISTA
  bc2:
  - B2M
  - Carbonic Anhydrase
  - CD11c
  - CD14
  - CD15
  - CD16
  - CD163
  - CD20
  - CD206
  - CD27
  - CD3
  - CD303
  - CD33
  - CD38
  - CD4
  - CD40
  - CD45RA
  - CD45RO
  - CD68
  - CD7
  - CD8a
  - cl.PARP
  - DNA1
  - DNA2
  - Ecad
  - FOXP3
  - GrzB
  - Histone H3
  - HLADR
  - ICOS
  - Ido1
  - Ki67
  - LAG3
  - MPO
  - PD1
  - PDGFRb
  - PDL1
  - SMA
  - TCF7
  - VISTA
  danenberg:
  - B2M
  - c-Caspase3c-PARP
  - Caveolin-1
  - CD11c
  - CD134
  - CD15
  - CD16
  - CD163
  - CD20
  - CD3
  - CD31-vWF
  - CD38
  - CD4
  - CD45RA
  - CD45RO
  - CD57
  - CD68
  - CD8a
  - CK5
  - CK8-18
  - CXCL12
  - DNA1
  - DNA2
  - ER
  - FOXP3
  - FSP1
  - GITR
  - HER2 (3B5)
  - HER2 (D8F12)
  - Histone H3
  - HLA-ABC
  - HLADR
  - ICOS
  - Ki67
  - panCK
  - PD1
  - PDGFRb
  - Podoplanin
  - SMA
  haley_glio:
  - B2M
  - CD109
  - CD11b
  - CD11c
  - CD14
  - CD16
  - CD163
  - CD206
  - CD235ab
  - CD3
  - CD31
  - CD4
  - CD44
  - CD45
  - CD66b
  - CD68
  - CD74
  - CD8a
  - DNA1
  - DNA2
  - Fibrinogen
  - GFAP
  - GLUT1
  - GrzB
  - HIF1a
  - HLADR
  - IBA1
  - Ki67
  - Met
  - Nestin
  - Olig2
  - P2RY12
  - panCK
  - pERK
  - S100B
  - SMA
  - Sox2
  - TMEM119
  - Vimentin
  - VISTA
  susman:
  - beta-Actin
  - C-peptide
  - CA2
  - CD11b
  - CD14
  - CD20
  - CD3
  - CD31
  - CD4
  - CD44
  - CD45
  - CD45RO
  - CD56
  - CD57
  - CD68
  - CD8a
  - CD99
  - Collagen Type I
  - DNA1
  - DNA2
  - FOXP3
  - GCG
  - GHRL
  - GrzB
  - HLA-ABC
  - HLADR
  - Ki67
  - Nestin
  - NFkb
  - NKX6-1
  - panCK
  - PDX1
  - PP
  - pS6
  - Somatostatin
  jackson-basel:
  - beta-Catenin
  - c-Caspase3c-PARP
  - c-Myc
  - Carbonic Anhydrase
  - CD20
  - CD3
  - CD44
  - CD45
  - CD68
  - CK14
  - CK19
  - CK5
  - CK7
  - CK8-18
  - DNA1
  - DNA2
  - Ecad
  - EGFR
  - EPCAM
  - ER
  - Fibronectin
  - GATA3
  - HER2 (3B5)
  - Histone H3
  - Histone H3 - p
  - Histone H3 - t
  - Ki67
  - mTOR
  - p53
  - panCK
  - pERK
  - PR
  - pS6
  - Slug
  - SMA
  - Sox9
  - Twist
  - Vimentin
  - vWF
  jackson-zurich:
  - beta-Catenin
  - c-Caspase3c-PARP
  - c-Myc
  - Carbonic Anhydrase
  - CD20
  - CD3
  - CD44
  - CD45
  - CD68
  - CK14
  - CK19
  - CK5
  - CK7
  - CK8-18
  - DNA1
  - DNA2
  - Ecad
  - EGFR
  - EPCAM
  - ER
  - Fibronectin
  - GATA3
  - HER2 (3B5)
  - Histone H3
  - Histone H3 - p
  - Histone H3 - t
  - Ki67
  - mTOR
  - p53
  - panCK
  - pERK
  - PR
  - pS6
  - Slug
  - SMA
  - Sox9
  - Twist
  - Vimentin
  - vWF
  hoch-protein:
  - beta-Catenin
  - Caveolin-1
  - CD11b
  - CD11c
  - CD15
  - CD19
  - CD20
  - CD206
  - CD3
  - CD303
  - CD38
  - CD4
  - CD45
  - CD45RA
  - CD45RO
  - CD68
  - CD7
  - CD8a
  - cl.PARP
  - Collagen Type I
  - CXCR2
  - DNA1
  - DNA2
  - FOXP3
  - GrzB
  - Histone H3
  - Histone H3 k27me3
  - HLADR
  - ICOS
  - Ido1
  - Ki67
  - Ki67-pt198
  - MITF
  - MPO
  - p75
  - PD1
  - PDL1
  - pERK
  - pS6
  - S100B
  - SMA
  - Sox10
  - Sox9
  - TCF1/7
  - TOX
  - Vimentin
  bengsch:
  - beta-Catenin
  - CD103
  - CD15
  - CD163
  - CD20
  - CD204
  - CD3
  - CD33
  - CD34
  - CD38
  - CD39
  - CD4
  - CD45
  - CD45RO
  - CD68
  - CD69
  - CD8a
  - CK7
  - Collagen Type I
  - CXCR5
  - CXCR6
  - DNA1
  - DNA2
  - Ecad
  - EOMES
  - FOXP3
  - GrzB
  - Histone H3
  - HLADR
  - Ki67
  - LAG3
  - LYVE1
  - PD1
  - PDL1
  - pERK
  - S6
  - SMA
  - TBET
  - TCF1
  - TIGIT
  - Tim3
  - TOX
  cords:
  - Cadherin-11
  - Carbonic Anhydrase
  - Caveolin-1
  - CCL21
  - CD10
  - CD146
  - CD15
  - CD20
  - CD248
  - CD3
  - CD31-vWF
  - CD34
  - CD4
  - CD45
  - CD68
  - CD73
  - CD8a
  - CXCL12
  - DNA1
  - DNA2
  - FAP
  - FOXP3
  - FSP1
  - Histone H3
  - HLADR
  - Ido1
  - K-Cadherin
  - Ki67
  - LYVE1
  - MMP11
  - MMP9
  - MPO
  - p75
  - panCK
  - PD1
  - PDGFRb
  - PNAd
  - Podoplanin
  - SMA
  - TCF1/7
  - VCAM1
  - Vimentin
  cords-fibro:
  - Cadherin-11
  - Carbonic Anhydrase
  - Caveolin-1
  - CCL21
  - CD10
  - CD146
  - CD15
  - CD20
  - CD248
  - CD3
  - CD31-vWF
  - CD34
  - CD4
  - CD45
  - CD68
  - CD73
  - CD8a
  - CXCL12
  - DNA1
  - DNA2
  - FAP
  - FOXP3
  - FSP1
  - Histone H3
  - HLADR
  - Ido1
  - K-Cadherin
  - Ki67
  - LYVE1
  - MMP11
  - MMP9
  - MPO
  - p75
  - panCK
  - PD1
  - PDGFRb
  - PNAd
  - Podoplanin
  - SMA
  - TCF1/7
  - VCAM1
  - Vimentin
  einhaus_2025:
  - CD11b
  - CD11c
  - CD14
  - CD15
  - CD16
  - CD163
  - CD20
  - CD206
  - CD209
  - CD3
  - CD31
  - CD36
  - CD4
  - CD44
  - CD45
  - CD45RA
  - CD56
  - CD68
  - CD8a
  - Collagen Type I
  - DNA1
  - DNA2
  - Ecad
  - FOXP3
  - GrzB
  - Histone H3
  - HLADR
  - Ki67
  - panCK
  - pCREB
  - PCSK2
  - pERK
  - pMAPKAPK2
  - pNFkB
  - pp38
  - pS6
  - pSTAT1
  - pSTAT3
  - SMA
  - VEGF
  - Vimentin
  ohara:
  - CD11b
  - CD11c
  - CD16
  - CD163
  - CD20
  - CD206
  - CD3
  - CD31
  - CD4
  - CD45
  - CD45RO
  - CD68
  - CD8a
  - CK5
  - Collagen Type I
  - DNA1
  - DNA2
  - Ecad
  - FOXP3
  - GATA3
  - GrzB
  - Histone H3
  - Ki67
  - panCK
  - PD1
  - PDL1
  - SMA
  - Vimentin
